const DOMAIN_ERROR_CODES = new Set([
  "CASE_NOT_FOUND",
  "FORBIDDEN",
  "INVALID_AMOUNT",
  "INVALID_EXPENSE_RECORD",
  "EXPENSE_EVIDENCE_REQUIRED",
  "INVALID_TARGET_AMOUNT",
  "INVALID_SUPPORTED_AT",
  "INVALID_SCREENSHOT_FILE_ID",
  "INVALID_ASSET_FILE_ID",
  "INVALID_PROFILE_ASSET_FILE_ID",
  "INVALID_CASE_PROFILE",
  "INVALID_RECORD_DETAIL_INPUT",
  "RECORD_NOT_FOUND",
  "INVALID_STATUS",
  "INVALID_TEXT",
  "SUPPORT_ENTRY_NOT_FOUND",
  "DUPLICATE_SUPPORT_SCREENSHOT",
  "SUPPORT_ENTRY_RATE_LIMIT_10_MIN",
  "SUPPORT_ENTRY_RATE_LIMIT_24_HOUR",
]);

export function isDomainErrorCode(code: unknown) {
  return typeof code === "string" && DOMAIN_ERROR_CODES.has(code);
}

export function getDomainErrorCodes() {
  return [...DOMAIN_ERROR_CODES];
}
